apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: solve-extract-find-sources-deployment
  name: solve-extract-find-sources-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: solve-extract-find-sources-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solve-extract-find-sources-deployment
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: solve-extract-find-sources-deployment-config
        image: gcr.io/panoptes-survey/solve-extract@sha256:2bde3a47fd43e8e1bffec6fb81c741b232f1184bd89ac0d12cc4fe2ef03c16e7
        imagePullPolicy: Always
        name: solve-extract-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        for: solver
