apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: similar-source-finder-deployment
  name: similar-source-finder-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647.0
  replicas: 1.0
  revisionHistoryLimit: 10.0
  selector:
    matchLabels:
      app: similar-source-finder-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1.0
      maxUnavailable: 1.0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: similar-source-finder-deployment
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: solve-and-extract-deployment-config
        image: gcr.io/panoptes-survey/find-similar-sources@sha256:7f0cd90c1d445cec035b1ba482ded79c8878e9ceddf986eafd6ea3ef6a735e61
        imagePullPolicy: Always
        name: similar-source-finder-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30.0
